language: node_js
node_js:
  - 'stable'
cache:
  yarn: true
branches:
  only:
  - /.*/
install: yarn install
services:
  - postgresql
before_script:
  - psql --host='ec2-174-129-226-232.compute-1.amazonaws.com' --port=5432 --username='nsngswqcrqecjy' --password --dbname='d185k31arfammj'
  - process.env.PGPASSWORD
script:
  - yarn run test
